import Foundation
import SwiftData

enum MuscleGroup: String, Codable, CaseIterable, Identifiable {
    case chest, back, shoulders, arms, legs, core, fullBody, other

    var id: Self { self }

    var label: String {
        switch self {
        case .chest: return "Chest"
        case .back: return "Back"
        case .shoulders: return "Shoulders"
        case .arms: return "Arms"
        case .legs: return "Legs"
        case .core: return "Core"
        case .fullBody: return "Full Body"
        case .other: return "Other"
        }
    }

    var icon: String {
        switch self {
        case .chest: return "figure.strengthtraining.traditional"
        case .back: return "figure.rower"
        case .shoulders: return "figure.arms.open"
        case .arms: return "dumbbell.fill"
        case .legs: return "figure.squat"
        case .core: return "figure.core.training"
        case .fullBody: return "figure.mixed.cardio"
        case .other: return "ellipsis.circle.fill"
        }
    }
}

@Model
final class Exercise {
    var name: String = ""
    var muscleGroupRaw: String = MuscleGroup.other.rawValue
    var isCustom: Bool = false

    @Relationship(deleteRule: .nullify, inverse: \LoggedSet.exercise)
    var loggedSets: [LoggedSet]? = []

    @Relationship(deleteRule: .nullify, inverse: \TemplateExerciseEntry.exercise)
    var templateEntries: [TemplateExerciseEntry]? = []

    init(name: String, muscleGroup: MuscleGroup, isCustom: Bool = false) {
        self.name = name
        self.muscleGroupRaw = muscleGroup.rawValue
        self.isCustom = isCustom
    }

    var muscleGroup: MuscleGroup {
        get { MuscleGroup(rawValue: muscleGroupRaw) ?? .other }
        set { muscleGroupRaw = newValue.rawValue }
    }

    static let starterExercises: [(name: String, muscleGroup: MuscleGroup)] = [
        // Chest
        ("Bench Press", .chest),
        ("Incline Bench Press", .chest),
        ("Decline Bench Press", .chest),
        ("Incline Dumbbell Press", .chest),
        ("Flat Dumbbell Press", .chest),
        ("Decline Dumbbell Press", .chest),
        ("Push-Up", .chest),
        ("Dips (Chest)", .chest),
        ("Cable Fly", .chest),
        ("Dumbbell Fly", .chest),
        ("Pec Deck Machine", .chest),
        ("Chest Press Machine", .chest),
        ("Landmine Press", .chest),

        // Back
        ("Barbell Row", .back),
        ("Pendlay Row", .back),
        ("Dumbbell Row", .back),
        ("T-Bar Row", .back),
        ("Seated Cable Row", .back),
        ("Pull-Up", .back),
        ("Chin-Up", .back),
        ("Lat Pulldown", .back),
        ("Close-Grip Lat Pulldown", .back),
        ("Deadlift", .back),
        ("Sumo Deadlift", .back),
        ("Rack Pull", .back),
        ("Straight-Arm Pulldown", .back),
        ("Face Pull", .back),
        ("Good Morning", .back),
        ("Back Extension", .back),

        // Shoulders
        ("Overhead Press", .shoulders),
        ("Seated Dumbbell Shoulder Press", .shoulders),
        ("Arnold Press", .shoulders),
        ("Push Press", .shoulders),
        ("Lateral Raise", .shoulders),
        ("Cable Lateral Raise", .shoulders),
        ("Front Raise", .shoulders),
        ("Rear Delt Fly", .shoulders),
        ("Upright Row", .shoulders),
        ("Shrug", .shoulders),

        // Arms
        ("Bicep Curl", .arms),
        ("Barbell Curl", .arms),
        ("Hammer Curl", .arms),
        ("Preacher Curl", .arms),
        ("Concentration Curl", .arms),
        ("Cable Curl", .arms),
        ("Tricep Pushdown", .arms),
        ("Overhead Tricep Extension", .arms),
        ("Skull Crusher", .arms),
        ("Tricep Kickback", .arms),
        ("Dips (Triceps)", .arms),
        ("Close-Grip Bench Press", .arms),
        ("Wrist Curl", .arms),

        // Legs
        ("Back Squat", .legs),
        ("Front Squat", .legs),
        ("Goblet Squat", .legs),
        ("Hack Squat", .legs),
        ("Bulgarian Split Squat", .legs),
        ("Romanian Deadlift", .legs),
        ("Stiff-Leg Deadlift", .legs),
        ("Leg Press", .legs),
        ("Leg Extension", .legs),
        ("Leg Curl", .legs),
        ("Walking Lunge", .legs),
        ("Reverse Lunge", .legs),
        ("Step-Up", .legs),
        ("Hip Thrust", .legs),
        ("Glute Bridge", .legs),
        ("Calf Raise", .legs),
        ("Seated Calf Raise", .legs),
        ("Box Jump", .legs),

        // Core
        ("Plank", .core),
        ("Side Plank", .core),
        ("Hanging Leg Raise", .core),
        ("Hanging Knee Raise", .core),
        ("Sit-Up", .core),
        ("Crunch", .core),
        ("Cable Crunch", .core),
        ("Russian Twist", .core),
        ("Ab Wheel Rollout", .core),
        ("Mountain Climber", .core),
        ("Flutter Kick", .core),
        ("Wood Chopper", .core),

        // Full Body
        ("Clean and Jerk", .fullBody),
        ("Power Clean", .fullBody),
        ("Snatch", .fullBody),
        ("Kettlebell Swing", .fullBody),
        ("Thruster", .fullBody),
        ("Burpee", .fullBody),
        ("Farmer's Carry", .fullBody),
        ("Turkish Get-Up", .fullBody),

        // Chest (additional)
        ("Alternating Floor Press", .chest),
        ("Around The Worlds", .chest),
        ("Barbell Bench Press - Medium Grip", .chest),
        ("Barbell Guillotine Bench Press", .chest),
        ("Bent-Arm Dumbbell Pullover", .chest),
        ("Bodyweight Flyes", .chest),
        ("Butterfly", .chest),
        ("Cable Chest Press", .chest),
        ("Cable Crossover", .chest),
        ("Clock Push-Up", .chest),
        ("Decline Barbell Bench Press", .chest),
        ("Decline Dumbbell Bench Press", .chest),
        ("Decline Dumbbell Flyes", .chest),
        ("Decline Push-Up", .chest),
        ("Dips - Chest Version", .chest),
        ("Dumbbell Bench Press", .chest),
        ("Dumbbell Flyes", .chest),
        ("Flat Bench Cable Flyes", .chest),
        ("Front Raise And Pullover", .chest),
        ("Hammer Grip Incline DB Bench Press", .chest),
        ("Incline Cable Chest Press", .chest),
        ("Incline Cable Flye", .chest),
        ("Incline Dumbbell Flyes", .chest),
        ("Incline Push-Up", .chest),
        ("Incline Push-Up Medium", .chest),
        ("Incline Push-Up Reverse Grip", .chest),
        ("Incline Push-Up Wide", .chest),
        ("Isometric Wipers", .chest),
        ("Leg-Over Floor Press", .chest),
        ("Leverage Chest Press", .chest),
        ("Leverage Decline Chest Press", .chest),
        ("Leverage Incline Chest Press", .chest),
        ("Low Cable Crossover", .chest),
        ("Machine Bench Press", .chest),
        ("Neck Press", .chest),
        ("One Arm Dumbbell Bench Press", .chest),
        ("One-Arm Flat Bench Dumbbell Flye", .chest),
        ("One-Arm Kettlebell Floor Press", .chest),
        ("Plyo Kettlebell Pushups", .chest),
        ("Push Up to Side Plank", .chest),
        ("Push-Up Wide", .chest),
        ("Push-Ups With Feet Elevated", .chest),
        ("Single-Arm Cable Crossover", .chest),
        ("Single-Arm Push-Up", .chest),
        ("Standing Cable Chest Press", .chest),
        ("Straight-Arm Dumbbell Pullover", .chest),
        ("Svend Press", .chest),
        ("Wide-Grip Barbell Bench Press", .chest),
        ("Wide-Grip Decline Barbell Pullover", .chest),

        // Back (additional)
        ("Alternating Kettlebell Row", .back),
        ("Alternating Renegade Row", .back),
        ("Barbell Deadlift", .back),
        ("Barbell Shrug", .back),
        ("Barbell Shrug Behind The Back", .back),
        ("Bent Over Barbell Row", .back),
        ("Bent Over One-Arm Long Bar Row", .back),
        ("Bent Over Two-Arm Long Bar Row", .back),
        ("Bent Over Two-Dumbbell Row", .back),
        ("Bent-Arm Barbell Pullover", .back),
        ("Bodyweight Mid Row", .back),
        ("Cable Incline Pushdown", .back),
        ("Cable Shrugs", .back),
        ("Calf-Machine Shoulder Shrug", .back),
        ("Close-Grip Front Lat Pulldown", .back),
        ("Deficit Deadlift", .back),
        ("Dumbbell Incline Row", .back),
        ("Dumbbell Shrug", .back),
        ("Elevated Cable Rows", .back),
        ("Full Range-Of-Motion Lat Pulldown", .back),
        ("Gironda Sternum Chins", .back),
        ("Hyperextensions (Back Extensions)", .back),
        ("Incline Bench Pull", .back),
        ("Inverted Row", .back),
        ("Inverted Row with Straps", .back),
        ("Kettlebell Sumo High Pull", .back),
        ("Kipping Muscle Up", .back),
        ("Kneeling High Pulley Row", .back),
        ("Leverage High Row", .back),
        ("Leverage Iso Row", .back),
        ("Leverage Shrug", .back),
        ("Lying Cambered Barbell Row", .back),
        ("Lying T-Bar Row", .back),
        ("Middle Back Shrug", .back),
        ("Mixed Grip Chin", .back),
        ("Muscle Up", .back),
        ("One Arm Chin-Up", .back),
        ("One Arm Lat Pulldown", .back),
        ("One-Arm Dumbbell Row", .back),
        ("One-Arm Kettlebell Row", .back),
        ("One-Arm Long Bar Row", .back),
        ("Reverse Grip Bent-Over Rows", .back),
        ("Rope Climb", .back),
        ("Rope Straight-Arm Pulldown", .back),
        ("Scapular Pull-Up", .back),
        ("Seated Good Mornings", .back),
        ("Seated One-arm Cable Pulley Rows", .back),
        ("Shotgun Row", .back),
        ("Side To Side Chins", .back),
        ("Standing Dumbbell Upright Row", .back),
        ("Stiff Leg Barbell Good Morning", .back),
        ("Straight Bar Bench Mid Rows", .back),
        ("T-Bar Row with Handle", .back),
        ("Two-Arm Kettlebell Row", .back),
        ("Underhand Cable Pulldowns", .back),
        ("Upright Cable Row", .back),
        ("V-Bar Pulldown", .back),
        ("V-Bar Pullup", .back),
        ("Weighted Ball Hyperextension", .back),
        ("Weighted Pull Ups", .back),
        ("Wide-Grip Lat Pulldown", .back),
        ("Wide-Grip Pulldown Behind The Neck", .back),
        ("Wide-Grip Rear Pull-Up", .back),

        // Shoulders (additional)
        ("Alternating Cable Shoulder Press", .shoulders),
        ("Alternating Deltoid Raise", .shoulders),
        ("Alternating Kettlebell Press", .shoulders),
        ("Arnold Dumbbell Press", .shoulders),
        ("Barbell Incline Shoulder Raise", .shoulders),
        ("Barbell Rear Delt Row", .shoulders),
        ("Barbell Shoulder Press", .shoulders),
        ("Bent Over Low-Pulley Side Lateral", .shoulders),
        ("Cable Internal Rotation", .shoulders),
        ("Cable Rear Delt Fly", .shoulders),
        ("Cable Rope Rear-Delt Rows", .shoulders),
        ("Cable Seated Lateral Raise", .shoulders),
        ("Cable Shoulder Press", .shoulders),
        ("Clean and Press", .shoulders),
        ("Cuban Press", .shoulders),
        ("Double Kettlebell Push Press", .shoulders),
        ("Double Kettlebell Snatch", .shoulders),
        ("Dumbbell Incline Shoulder Raise", .shoulders),
        ("Dumbbell Lying Rear Lateral Raise", .shoulders),
        ("Dumbbell One-Arm Shoulder Press", .shoulders),
        ("Dumbbell One-Arm Upright Row", .shoulders),
        ("Dumbbell Raise", .shoulders),
        ("Dumbbell Scaption", .shoulders),
        ("Dumbbell Shoulder Press", .shoulders),
        ("External Rotation", .shoulders),
        ("External Rotation with Cable", .shoulders),
        ("Front Cable Raise", .shoulders),
        ("Front Dumbbell Raise", .shoulders),
        ("Front Incline Dumbbell Raise", .shoulders),
        ("Front Plate Raise", .shoulders),
        ("Front Two-Dumbbell Raise", .shoulders),
        ("Handstand Push-Ups", .shoulders),
        ("Kettlebell Arnold Press", .shoulders),
        ("Kettlebell Seated Press", .shoulders),
        ("Kettlebell Thruster", .shoulders),
        ("Landmine Linear Jammer", .shoulders),
        ("Leverage Shoulder Press", .shoulders),
        ("Low Pulley Row To Neck", .shoulders),
        ("Lying One-Arm Lateral Raise", .shoulders),
        ("Lying Rear Delt Raise", .shoulders),
        ("Machine Shoulder (Military) Press", .shoulders),
        ("One-Arm Incline Lateral Raise", .shoulders),
        ("One-Arm Kettlebell Push Press", .shoulders),
        ("One-Arm Kettlebell Snatch", .shoulders),
        ("One-Arm Side Laterals", .shoulders),
        ("Power Partials", .shoulders),
        ("Reverse Flyes", .shoulders),
        ("Reverse Machine Flyes", .shoulders),
        ("Seated Barbell Military Press", .shoulders),
        ("Seated Bent-Over Rear Delt Raise", .shoulders),
        ("Seated Cable Shoulder Press", .shoulders),
        ("Seated Dumbbell Press", .shoulders),
        ("Seated Side Lateral Raise", .shoulders),
        ("Side Lateral Raise", .shoulders),
        ("Side Laterals to Front Raise", .shoulders),
        ("Single Dumbbell Raise", .shoulders),
        ("Single-Arm Linear Jammer", .shoulders),
        ("Standing Barbell Press Behind Neck", .shoulders),
        ("Standing Dumbbell Press", .shoulders),
        ("Standing Low-Pulley Deltoid Raise", .shoulders),
        ("Standing Military Press", .shoulders),
        ("Standing Palms-In Dumbbell Press", .shoulders),
        ("Straight Raises on Incline Bench", .shoulders),
        ("Two-Arm Kettlebell Clean", .shoulders),
        ("Two-Arm Kettlebell Military Press", .shoulders),
        ("Upright Barbell Row", .shoulders),

        // Arms (additional)
        ("Alternate Hammer Curl", .arms),
        ("Alternate Incline Dumbbell Curl", .arms),
        ("Bench Dips", .arms),
        ("Bench Press - Powerlifting", .arms),
        ("Board Press", .arms),
        ("Body Tricep Press", .arms),
        ("Cable Incline Triceps Extension", .arms),
        ("Cable Lying Triceps Extension", .arms),
        ("Cable One Arm Tricep Extension", .arms),
        ("Cable Preacher Curl", .arms),
        ("Cable Wrist Curl", .arms),
        ("Close-Grip Barbell Bench Press", .arms),
        ("Close-Grip Dumbbell Press", .arms),
        ("Close-Grip EZ Bar Curl", .arms),
        ("Close-Grip EZ-Bar Press", .arms),
        ("Close-Grip Standing Barbell Curl", .arms),
        ("Cross Body Hammer Curl", .arms),
        ("Decline Dumbbell Triceps Extension", .arms),
        ("Decline EZ Bar Triceps Extension", .arms),
        ("Dip Machine", .arms),
        ("Dips - Triceps Version", .arms),
        ("Drag Curl", .arms),
        ("Dumbbell Alternate Bicep Curl", .arms),
        ("Dumbbell Bicep Curl", .arms),
        ("Dumbbell Floor Press", .arms),
        ("Dumbbell Lying Pronation", .arms),
        ("Dumbbell Lying Supination", .arms),
        ("Dumbbell One-Arm Triceps Extension", .arms),
        ("Dumbbell Prone Incline Curl", .arms),
        ("EZ-Bar Curl", .arms),
        ("EZ-Bar Skullcrusher", .arms),
        ("Finger Curls", .arms),
        ("Flexor Incline Dumbbell Curls", .arms),
        ("Floor Press", .arms),
        ("High Cable Curls", .arms),
        ("Incline Barbell Triceps Extension", .arms),
        ("Incline Dumbbell Curl", .arms),
        ("Incline Hammer Curls", .arms),
        ("Incline Inner Biceps Curl", .arms),
        ("Incline Push-Up Close-Grip", .arms),
        ("JM Press", .arms),
        ("Kneeling Cable Triceps Extension", .arms),
        ("Low Cable Triceps Extension", .arms),
        ("Lying Cable Curl", .arms),
        ("Lying Dumbbell Tricep Extension", .arms),
        ("Lying High Bench Barbell Curl", .arms),
        ("Lying Supine Dumbbell Curl", .arms),
        ("Lying Triceps Press", .arms),
        ("Machine Bicep Curl", .arms),
        ("Machine Preacher Curls", .arms),
        ("Machine Triceps Extension", .arms),
        ("One Arm Dumbbell Preacher Curl", .arms),
        ("One Arm Floor Press", .arms),
        ("Overhead Cable Curl", .arms),
        ("Palms-Down Wrist Curl Over A Bench", .arms),
        ("Parallel Bar Dip", .arms),
        ("Pin Presses", .arms),
        ("Plate Pinch", .arms),
        ("Preacher Hammer Dumbbell Curl", .arms),
        ("Push-Ups - Close Triceps Position", .arms),
        ("Reverse Barbell Curl", .arms),
        ("Reverse Barbell Preacher Curls", .arms),
        ("Reverse Cable Curl", .arms),
        ("Reverse Grip Triceps Pushdown", .arms),
        ("Reverse Plate Curls", .arms),
        ("Reverse Triceps Bench Press", .arms),
        ("Ring Dips", .arms),
        ("Seated Dumbbell Curl", .arms),
        ("Seated Dumbbell Inner Biceps Curl", .arms),
        ("Seated Palm-Up Barbell Wrist Curl", .arms),
        ("Seated Triceps Press", .arms),
        ("Spider Curl", .arms),
        ("Standing Biceps Cable Curl", .arms),
        ("Standing Concentration Curl", .arms),
        ("Standing Dumbbell Reverse Curl", .arms),
        ("Standing Inner-Biceps Curl", .arms),
        ("Standing One-Arm Cable Curl", .arms),
        ("Standing Towel Triceps Extension", .arms),
        ("Tate Press", .arms),
        ("Tricep Dumbbell Kickback", .arms),
        ("Triceps Pushdown", .arms),
        ("Triceps Pushdown - Rope Attachment", .arms),
        ("Two-Arm Dumbbell Preacher Curl", .arms),
        ("Weighted Bench Dip", .arms),
        ("Wide-Grip Standing Barbell Curl", .arms),
        ("Wrist Roller", .arms),
        ("Wrist Rotations with Straight Bar", .arms),
        ("Zottman Curl", .arms),
        ("Zottman Preacher Curl", .arms),

        // Legs (additional)
        ("Ball Leg Curl", .legs),
        ("Barbell Full Squat", .legs),
        ("Barbell Glute Bridge", .legs),
        ("Barbell Hack Squat", .legs),
        ("Barbell Hip Thrust", .legs),
        ("Barbell Lunge", .legs),
        ("Barbell Seated Calf Raise", .legs),
        ("Barbell Side Split Squat", .legs),
        ("Barbell Squat", .legs),
        ("Barbell Squat To A Bench", .legs),
        ("Barbell Step Ups", .legs),
        ("Barbell Walking Lunge", .legs),
        ("Bodyweight Squat", .legs),
        ("Bodyweight Walking Lunge", .legs),
        ("Box Squat", .legs),
        ("Butt Lift (Bridge)", .legs),
        ("Cable Deadlifts", .legs),
        ("Cable Hip Adduction", .legs),
        ("Calf Press", .legs),
        ("Calf Raise On A Dumbbell", .legs),
        ("Donkey Calf Raises", .legs),
        ("Dumbbell Clean", .legs),
        ("Dumbbell Lunges", .legs),
        ("Dumbbell Rear Lunge", .legs),
        ("Dumbbell Seated One-Leg Calf Raise", .legs),
        ("Dumbbell Squat", .legs),
        ("Dumbbell Squat To A Bench", .legs),
        ("Dumbbell Step Ups", .legs),
        ("Elevated Back Lunge", .legs),
        ("Floor Glute-Ham Raise", .legs),
        ("Freehand Jump Squat", .legs),
        ("Front Barbell Squat", .legs),
        ("Front Barbell Squat To A Bench", .legs),
        ("Front Squat (Clean Grip)", .legs),
        ("Front Squats With Two Kettlebells", .legs),
        ("Glute Ham Raise", .legs),
        ("Glute Kickback", .legs),
        ("Good Morning off Pins", .legs),
        ("Hanging Bar Good Morning", .legs),
        ("Kettlebell One-Legged Deadlift", .legs),
        ("Kettlebell Pistol Squat", .legs),
        ("Kneeling Squat", .legs),
        ("Leg Lift", .legs),
        ("Leverage Deadlift", .legs),
        ("Lunge Pass Through", .legs),
        ("Lunge Sprint", .legs),
        ("Lying Leg Curls", .legs),
        ("Lying Machine Squat", .legs),
        ("Narrow Stance Hack Squats", .legs),
        ("Narrow Stance Leg Press", .legs),
        ("Narrow Stance Squats", .legs),
        ("Natural Glute Ham Raise", .legs),
        ("One Leg Barbell Squat", .legs),
        ("One-Arm Kettlebell Clean", .legs),
        ("One-Arm Kettlebell Swings", .legs),
        ("One-Arm Overhead Kettlebell Squats", .legs),
        ("One-Arm Side Deadlift", .legs),
        ("One-Legged Cable Kickback", .legs),
        ("Plie Dumbbell Squat", .legs),
        ("Prone Manual Hamstring", .legs),
        ("Pull Through", .legs),
        ("Reverse Hyperextension", .legs),
        ("Rocking Standing Calf Raise", .legs),
        ("Seated Leg Curl", .legs),
        ("Single Leg Glute Bridge", .legs),
        ("Single-Leg High Box Squat", .legs),
        ("Single-Leg Leg Extension", .legs),
        ("Snatch Pull", .legs),
        ("Speed Box Squat", .legs),
        ("Speed Squats", .legs),
        ("Split Squat with Dumbbells", .legs),
        ("Squat with Plate Movers", .legs),
        ("Standing Barbell Calf Raise", .legs),
        ("Standing Calf Raises", .legs),
        ("Standing Dumbbell Calf Raise", .legs),
        ("Standing Leg Curl", .legs),
        ("Step-up with Knee Raise", .legs),
        ("Stiff-Legged Barbell Deadlift", .legs),
        ("Stiff-Legged Dumbbell Deadlift", .legs),
        ("Thigh Abductor", .legs),
        ("Thigh Adductor", .legs),
        ("Trap Bar Deadlift", .legs),
        ("Weighted Jump Squat", .legs),
        ("Weighted Sissy Squat", .legs),
        ("Weighted Squat", .legs),
        ("Wide Stance Barbell Squat", .legs),
        ("Zercher Squats", .legs),

        // Core (additional)
        ("3/4 Sit-Up", .core),
        ("Ab Crunch Machine", .core),
        ("Ab Roller", .core),
        ("Air Bike", .core),
        ("Barbell Ab Rollout", .core),
        ("Barbell Ab Rollout - On Knees", .core),
        ("Barbell Rollout from Bench", .core),
        ("Barbell Side Bend", .core),
        ("Bent-Knee Hip Raise", .core),
        ("Cable Reverse Crunch", .core),
        ("Cable Russian Twists", .core),
        ("Cable Seated Crunch", .core),
        ("Crunch - Hands Overhead", .core),
        ("Crunch - Legs On Exercise Ball", .core),
        ("Crunches", .core),
        ("Dead Bug", .core),
        ("Decline Crunch", .core),
        ("Decline Oblique Crunch", .core),
        ("Decline Reverse Crunch", .core),
        ("Dumbbell Side Bend", .core),
        ("Exercise Ball Crunch", .core),
        ("Exercise Ball Pull-In", .core),
        ("Flat Bench Leg Pull-In", .core),
        ("Flat Bench Lying Leg Raise", .core),
        ("Hanging Pike", .core),
        ("Jackknife Sit-Up", .core),
        ("Knee/Hip Raise On Parallel Bars", .core),
        ("Leg Pull-In", .core),
        ("Oblique Crunches", .core),
        ("Oblique Crunches - On The Floor", .core),
        ("One-Arm Medicine Ball Slam", .core),
        ("Pallof Press", .core),
        ("Pallof Press With Rotation", .core),
        ("Plate Twist", .core),
        ("Reverse Crunch", .core),
        ("Rope Crunch", .core),
        ("Seated Barbell Twist", .core),
        ("Seated Flat Bench Leg Pull-In", .core),
        ("Seated Leg Tucks", .core),
        ("Side Bridge", .core),
        ("Side Jackknife", .core),
        ("Spider Crawl", .core),
        ("Standing Cable Lift", .core),
        ("Standing Cable Wood Chop", .core),
        ("Standing Rope Crunch", .core),
        ("Tuck Crunch", .core),
        ("Weighted Ball Side Bend", .core),
        ("Weighted Crunches", .core),
    ]
}
